# ServerProperties
server.port=8080
server.servlet.context-path=

# ThymeleafProperties：
# thymeleaf模板不缓存 [pro]：true
spring.thymeleaf.cache=true

# DataSourceProperties：
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000

# MybatisProperties：
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.nowcoder.community.entity
mybatis.configuration.useGeneratedKeys=true
mybatis.configuration.mapUnderscoreToCamelCase=true

# logger：
# 日志级别有 trace debug info warn error
#logging.level.com.nowcoder.community=debug
#logging.file.name=H:/code/testProject/java/data/nowcoder/community.log

# MailProperties：
# 新浪126 账号授权码：RTACSQATMTOUAESB
spring.mail.host=smtp.126.com
spring.mail.port=465
spring.mail.username=
spring.mail.password=
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.ssl.enable=true

# community [pro]
community.path.domain=http://39.107.118.139
community.path.upload=/tmp/community/uploads

# RedisProperties
spring.redis.database=11
spring.redis.host=localhost
spring.redis.port=6379

# KafkaProperties
## 配置服务器地址
spring.kafka.bootstrap-servers=localhost:9092
## 消费者组id
spring.kafka.consumer.group-id=community-consumer-group
## 是否自动提交消费者的偏移量(消费者读取消息是按偏移量读取)
spring.kafka.consumer.enable-auto-commit=true
## 自动提交的频率间隔
spring.kafka.consumer.auto-commit-interval=3000

# ElasticsearchProperties
spring.elasticsearch.rest.uris=http://localhost:9200

# TaskExecutionProperties
## 线程初始化数
spring.task.execution.pool.core-size=5
## 线程最大数
spring.task.execution.pool.max-size=15
## 队列容量：max-size线程不够用，则先将任务放到队列中，线程空闲再执行，起到缓冲作用
spring.task.execution.pool.queue-capacity=100

# TaskSchedulingProperties
## 可预判线程数量需求，只需配置线程数
## 线程数量
spring.task.scheduling.pool.size=5

# QuartzProperties
## job存储底层驱动
spring.quartz.job-store-type=jdbc
## 调度器名
spring.quartz.scheduler-name=communityScheduler
## 调度器id自动生成
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
## 任务存数据库所使用类
spring.quartz.properties.org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
## 任务存数据库使用驱动
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
## 是否采用集群方式
spring.quartz.properties.org.quartz.jobStore.isClustered=true
## 使用线程池
spring.quartz.properties.org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
## 线程数量
spring.quartz.properties.org.quartz.threadPool.threadCount=5

# wk 自定义 [pro]
wk.image.command=/opt/wkhtmltoimage.sh
wk.image.storage=/tmp/community/wk-images

# qiniu 自定义
qiniu.key.access=
qiniu.key.secret=
## 云空间名
qiniu.bucket.header.name=testproject--community-header
qiniu.bucket.header.url=http://qoporkm4q.hn-bkt.clouddn.com
qiniu.bucket.share.name=testproject--community-share
qiniu.bucket.share.url=http://qopolgk0t.hn-bkt.clouddn.com

# caffeine
## 缓存的帖子一般为前面几页，设置最多15页
caffeine.posts.max-size=15
## 缓存过期时间
caffeine.posts.expire-seconds=180

# actoator
## 端点暴露配置
management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=info,caches
