# MailProperties£º
spring.mail.username=xiedongze2021@126.com
spring.mail.password=RTACSQATMTOUAESB

# qiniu ×Ô¶¨Òå
qiniu.key.access=mEBQtvoh59JDottqP-rLr8yqcUeqOItEPeoQFkJE
qiniu.key.secret=6hKOIY6tSMPZko_LzM5XBW43NsKiRAK__6S3PBtJ